### PR TITLE
Shiny v1

### PR DESCRIPTION
**Pull request by jacmarjorie**
Uploaded the first version of the shiny interface with simple instructions in the readme. Future extensions include setting boundary conditions/types in the input fields. Ready to be merged.

### CODE REVIEW

**Comment by maximilianh** [comment]
Hi Jacelyn, interesting, I've never heard of shiny before...

I tried to install it but got:

package ‘shiny’ is not available (for R version 2.15.2)
package ‘json’ is not available (for R version 2.15.2)

Any ideas? Is my R too old?

I am wondering what the advantage of the shiny wrapper is. Is it really
serving the beacon webservice as a webservice again?

thanks!

Max

**Comment by jacmarjorie** [comment]
I think it just doesn't know what repository to use. Apparently, 2.15.2 doesn't point to the standard CRAN repo, but 2.15.3 does. Try to do:

install.packages('shiny', repos='http://cran.rstudio.com/')

Then repeat for 'rjson', and 'httr'.

Another solution would be to update your R version.

I think the advantage is to just have a user friendly way to query the beacon. For instance, when we adopt this for our beacon, this will provide a nice looking front end that abstracts from the command line.  It's really more for aesthetics and user friendliness, though for some people this can be a selling point.

Let me know how the above works out for you.
- Jaclyn

**Comment by maximilianh** [comment]
Hi Jaclyn,
thanks for this, I'm still getting the same message.

Do you have this running on a webserver that is accessible from outside so
I could test it on your server?

thanks
Max

**Comment by alyh** [comment]
I tried running this as well and had the same problem as @maximilianh

I installed the `libcurl4-gnutls-dev` package (See http://stackoverflow.com/a/20924082)

And that let me install the `httr` & `shiny` packages with no problem but I had to install rjson as:

`sudo apt-get install r-cran-rjson`

And then I curl'ed `http://localhost/cgi-bin/ucscBeacon` and got a 301 (relocated..) But this is just an ssh session so I can't see the ui anyway.

**Comment by maximilianh** [comment]
I think this is adding too many dependencies for a rather simple html page.
I completely agree with Jaclyn that the UI could better though. Does
someone have a screenshot or a demo server of this shiny interface? Or,
Jaclyn, could you save and send me the generated html page?
Maybe I can just use the shiny-generated html and use that in the script...
that would not add any dependency on R packages...

thanks!
Max

**Comment by alyh** [comment]
@maximilianh What are you looking for in the new ui? I can help make a simple html page without using any shiny dependencies

**Comment by maximilianh** [comment]
that would be awesome, of course! I'm not so good with modern css/js
webdesign. I originally thought that Jaclyn could give us a screenshot or
demo html page of her shiny interface. Otherwise, we could simply create an
html page that asks for the genome, chromosome, position, allele and shows
the result of the request?

**Comment by alyh** [comment]
That sounds reasonable. I created [this one](https://dcc.icgc.org/ga4gh/beacon) for ICGC but that uses a few dependencies like `AngularJS` and `jQuery` but we can create a simpler one with a similar structure here.

I'll make an issue and work away at it as I (or someone else) gets time

**Comment by alyh** [comment]
Even better would be if @jacmarjorie could give us the generated html page and we would have a great starting point

**Comment by maximilianh** [comment]
Yes, that would be great!

**Comment by jacmarjorie** [comment]
I can take the skeleton from the shiny interface and throw in an ajax request if you want - could do something this weekend. I agree that shiny has too many dependencies. I was playing around with it for another project. It's great for putting something together in minutes, but at the end of the day it doesn't have a lightweight feel. Closing this request.

**Pull request closed without merging**
