### PR TITLE
ui skeleton and dependencies

### PR DESCRIPTION
**Pull request by jacmarjorie**
I had to deal with a HW failure over the weekend, so I didn't have time to implement the query functionality. Though here is the skeleton in case Aly wants to take off from here - I can pick up on this late next week, if not. To view, just open index.html in the browser. Again, this can be improved by adding restrictions to fields, as right now every entry is a text field.

### CODE REVIEW

**Comment by alyh** [comment]
Thanks for this Jaclyn! 
To cut down on the files needed, can we use a CDN for `jquery`, `jqueryui` and `bootstrap`?

The head would look something like this:

``` HTML
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet" />
  <title>UCSC Beacon</title>
</head>
```

And then we only need `index.html` :)
Btw, this is what I see on the browser:
screen shot 2015-03-23 at 9 56 43 am

**Comment by jacmarjorie** [comment]
Yeah, that's another way to call in the dependencies, though then you are dependent on someone else's hosted files rather than your own. Up to you.

**Comment by maximilianh** [comment]
+1 for using CDNs.

Otherwise we'd tons of files in there for 3 input fields. It'd be nice to
keep the number of files to install low, I tried to put everything into a
single script file.

**Comment by alyh** [comment]
Looks good to me!

**Comment by maximilianh** [comment]
Sorry Jaclyn I had missed your last change. Looks very good to me!

**Pull request merged**
